### PR TITLE
Add linting and formatting to improve open source contributability

### PR DESCRIPTION
**Pull request by samschloegel**
Starting a conversation here about including `eslint` and `prettier` in the `devDependencies` in order to make contributing to this project easier / more manageable/consistent.

I've included the airbnb-base eslint extension here as an initial proposal but of course that isn't necessary - any preferred starting point would be great.

If you're up for something like this, I would be glad to go through the project and bring things into compliance with the prettier and eslint rules, continuing to commit to this pull request before it gets merged.

Let me know what you think!

Sam

### CODE REVIEW

**Comment by sparks-alec** [comment]
I'm extremely into this. Go for it! Shall I merge this or wait until you go through it?

**Comment by samschloegel** [comment]
> Shall I merge this or wait until you go through it?

Cool. I'll keep at it for a little bit before the merge.

**Comment by samschloegel** [comment]
@sparks-alec Is there any particular reason `main.js` requires 'electron-squirrel-startup' twice in a row at the top of the file? Can the second one be removed?

**Comment by samschloegel** [comment]
Please review changes in 9c16c9c
Reducing variable scope pollution may break code blocks that were working due to excessive scope
I don't think this will have broken anything but would be good to have another pair of eyes on it

**Pull request merged**
