### PR TITLE
X32 cleanup

### PR DESCRIPTION
**Pull request by jwetzell**
Fixed the inif symbol displayig `-&infin;` instead of `-∞` this 

- `/ch/lr` isn't a thing in the x32/m32 osc (maybe is with xair I don't have one anymore so can't test) as far as I can tell it is `/main/st` and `/main/m` for the stereo and mono channels so I added that in
- Added fetching of the main stereo name and color and added that to the template (it seems backwards as far as the color inversion looks but I will test some more).

### CODE REVIEW

**Comment by jwetzell** [comment]
BTW love this project and the potential it has!

**Comment by jwetzell** [comment]
Figured I would take a hack at the meters for X32 (would probably be a similar process for the XAir). It's real basic and I'm not a massive fan of the math to get to the end meter result but it lines up alright. This doesn't include the main LR meter.

**Comment by jwetzell** [comment]
Moved things to a class and rearranged the data to be a bit more extensible. Also added stereo metering for the main LR channel.

**Comment by sparks-alec** [comment]
Wow, this is awesome!! Thank you!

**Comment by jwetzell** [comment]
@sparks-alec This project pretty much ticks all the boxes for me. I've been slowly developing a very basic QLab control app for Android/iOS using OSC so quite familiar with OSC! I think this project has some serious potential!

**Comment by sparks-alec** [comment]
Looks like I'm not going to have IRL access to a X32 till next week - mind sharing screenshots?

**Comment by jwetzell** [comment]
Sorry, forgot to reply to this. I can see what I can do about getting screenshots!

**Comment by jwetzell** [comment]
If there is anything specific you'd like a picture of let me know. [IMAGES](https://imgur.com/a/RyOlDpe)

**Comment by sparks-alec** [comment]
Looks fantastic! Thank you!

**Comment by jwetzell** [comment]
Thanks! Like I said a lot of these updates are probably fairly transferable to the XAir lineup but I do not have one of those to test with.

**Pull request merged**
